source 'http://rubygems.org'
ruby '3.3.9'

gem 'capybara'
gem 'cucumber'
gem 'gherkin'
gem 'json'
gem 'require_all'
gem 'rspec'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'term-ansicolor'
gem 'xpath'
