source 'http://rubygems.org'
ruby '3.4.6'

gem 'capybara'
gem 'cucumber'
gem 'cucumber-gherkin'
gem 'json'
gem 'require_all'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-rspec'
gem 'rubocop-performance'
gem 'selenium-webdriver'
gem 'term-ansicolor'
gem 'xpath'
